### ISSUE TITLE
[Bug]: Sign text and EXP level changes to white when opening GUI with darkmode

### ISSUE THREAD

**Issue by xSaVageAU** [Fuzss/mindfuldarkness#12] opened 2023-06-12 12:29 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20

### Mod Version (Required)

v7.0.0 Fabric

### Notes (Required)

Sign text and EXP level changes to white, and colored sign text looks weird when opening a GUI with darkmode on. They return to normal when darkmode is turned off or exiting the GUI.
Not sure if it's intended or just a side effect of the mod. Either way it's not a big deal
Same thing also happens when chat is opened.

**Comment by Santiag09** [comment] 2023-06-19 11:32
Yeah, this issue is rather annoying

**Comment by Lxndwich** [comment] 2023-08-09 21:37
Can reproduce on Fabric 1.20.1

**Comment by Fuzss** [comment] 2023-08-10 13:49
Fixed in v8.0.1 for sign and chat screens.

Fixing the xp level display on all screens is not possible, since the font color adjustments cannot be selectively disabled for certain screen parts, and generally font adjustments are desired for darkened screens to keep text readable.

**Closed by Fuzss** 2023-08-10 13:49 UTC
Labels: bug
